//! Custom error types for the Qaren configuration comparison tool.
//!
//! All functions that can fail return `QarenResult<T>`. Errors are propagated
//! using the `?` operator. No `.unwrap()` or `.expect()` is used in production code.

use std::io;
use std::path::PathBuf;
use thiserror::Error;

/// Type alias for `Result<T, QarenError>`.
pub type QarenResult<T> = Result<T, QarenError>;

/// Comprehensive error type for all Qaren operations.
///
/// Each variant maps to a specific failure mode and produces a
/// user-friendly error message via the `Display` implementation
/// generated by `thiserror`.
#[derive(Error, Debug)]
pub enum QarenError {
    /// Failed to read a file from disk.
    #[error("Failed to read file '{path}': {source}")]
    FileRead {
        path: PathBuf,
        source: io::Error,
    },

    /// Failed to write a file to disk (e.g., patch generation).
    #[error("Failed to write file '{path}': {source}")]
    FileWrite {
        path: PathBuf,
        source: io::Error,
    },

    /// The specified file was not found.
    #[error("File not found: {0}")]
    FileNotFound(PathBuf),

    /// Permission denied when accessing a file.
    #[error("Permission denied for file: {0}")]
    PermissionDenied(PathBuf),

    /// The file contains invalid UTF-8 encoding.
    #[error("Invalid UTF-8 encoding in file '{path}' at line {line}")]
    InvalidEncoding {
        path: PathBuf,
        line: usize,
    },

    /// The specified delimiter is invalid (not a single character).
    #[error("Invalid delimiter: '{0}' (must be a single character)")]
    InvalidDelimiter(String),

    /// A parsing error occurred at a specific line.
    #[error("Parsing failed at line {line} in file '{path}': {reason}")]
    ParseError {
        path: PathBuf,
        line: usize,
        reason: String,
    },

    /// Invalid command-line arguments were provided.
    #[error("Invalid command-line arguments: {0}")]
    InvalidArguments(String),

    /// A generic I/O error occurred.
    #[error("IO error: {0}")]
    Io(#[from] io::Error),
}

impl QarenError {
    /// Convert an `io::Error` into a contextual `QarenError` based on the error kind.
    ///
    /// Maps `NotFound` → `FileNotFound`, `PermissionDenied` → `PermissionDenied`,
    /// and everything else → `FileRead`.
    pub fn from_io_with_path(err: io::Error, path: PathBuf) -> Self {
        match err.kind() {
            io::ErrorKind::NotFound => QarenError::FileNotFound(path),
            io::ErrorKind::PermissionDenied => QarenError::PermissionDenied(path),
            _ => QarenError::FileRead { path, source: err },
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_file_not_found_display() {
        let err = QarenError::FileNotFound(PathBuf::from("/tmp/missing.env"));
        assert_eq!(format!("{err}"), "File not found: /tmp/missing.env");
    }

    #[test]
    fn test_permission_denied_display() {
        let err = QarenError::PermissionDenied(PathBuf::from("/etc/secret.env"));
        assert_eq!(format!("{err}"), "Permission denied for file: /etc/secret.env");
    }

    #[test]
    fn test_invalid_delimiter_display() {
        let err = QarenError::InvalidDelimiter("abc".to_string());
        assert_eq!(
            format!("{err}"),
            "Invalid delimiter: 'abc' (must be a single character)"
        );
    }

    #[test]
    fn test_invalid_arguments_display() {
        let err = QarenError::InvalidArguments("missing file argument".to_string());
        assert_eq!(
            format!("{err}"),
            "Invalid command-line arguments: missing file argument"
        );
    }

    #[test]
    fn test_from_io_with_path_not_found() {
        let io_err = io::Error::new(io::ErrorKind::NotFound, "not found");
        let err = QarenError::from_io_with_path(io_err, PathBuf::from("test.env"));
        assert!(matches!(err, QarenError::FileNotFound(_)));
    }

    #[test]
    fn test_from_io_with_path_permission_denied() {
        let io_err = io::Error::new(io::ErrorKind::PermissionDenied, "denied");
        let err = QarenError::from_io_with_path(io_err, PathBuf::from("test.env"));
        assert!(matches!(err, QarenError::PermissionDenied(_)));
    }

    #[test]
    fn test_from_io_with_path_other() {
        let io_err = io::Error::new(io::ErrorKind::Other, "something else");
        let err = QarenError::from_io_with_path(io_err, PathBuf::from("test.env"));
        assert!(matches!(err, QarenError::FileRead { .. }));
    }

    #[test]
    fn test_io_error_from_conversion() {
        let io_err = io::Error::new(io::ErrorKind::BrokenPipe, "pipe broken");
        let err: QarenError = io_err.into();
        assert!(matches!(err, QarenError::Io(_)));
    }
}
